name: release

on:
  push:
    tags:
      - "v*"

env:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

jobs:
  check-version:
    name: check version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Export project version
        uses: ./.github/actions/export-project-version
      - name: Check version is semantic
        run: |
          echo $PROJECT_VERSION | egrep '^([0-9]+\.){1,2}([0-9])?$'

  build:
    name: build
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java 1.8
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk8'
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: .m2/repository/
          key: ${{ github.ref }}
      - name: Build the project
        run: mvn $MAVEN_CLI_OPTS package -DskipTests
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Build the project*'
          mention: 'here'
          mention_if: 'failure'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: build
    env:
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PWD: ${{ secrets.BINTRAY_PWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Export project version
        uses: ./.github/actions/export-project-version
      - name: Setup Java 1.8
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk8'
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: .m2/repository/
          key: ${{ github.ref }}
      - name: Publish on Bintray/JCenter
        run: mvn $MAVEN_CLI_OPTS deploy -DskipTests -Ddependency-check.skip=true
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Publish ${{ env.PROJECT_VERSION }} on Bintray/JCenter*'
          mention: 'here'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
